language: cpp
compiler:
  - clang
  - gcc

install:
  - .travis_scripts/cmake.sh
  - sudo apt-get install libcppunit-dev
  
script: 
  - mkdir build && cd build
  - cmake ../
  - make
  - test/MessageDiggest-testrunner